/**
 * Analysis storage.
 *
 * PostgreSQL would be overkill here. An analysis is a single self-contained
 * document that one browser session reads back a handful of times, so it is
 * written as JSON under `.brickthrift/analyses/` with an in-memory index in
 * front of it. That keeps `npm install && npm run dev` to two commands with no
 * database to provision, and the storage interface below is narrow enough that
 * swapping in Prisma later touches one file. See docs/ARCHITECTURE.md.
 *
 * The stored record keeps the ORIGINAL uploaded text verbatim. Every export and
 * every re-costing re-derives from it, so the user's source file is never
 * mutated and "Reset to original" cannot fail.
 */

import { mkdirSync, readFileSync, writeFileSync, existsSync, readdirSync, statSync, unlinkSync } from 'node:fs';
import path from 'node:path';

import type { AnalysisResult } from '../analysis/types';
import type { PriceQuote } from '../pricing/types';
import { getRuntimeConfig } from './config';

export interface StoredAnalysis {
  readonly result: AnalysisResult;
  /** The uploaded file, byte for byte. */
  readonly source: string;
  /** Every price quote the analysis used, so exports need no network access. */
  readonly quotes: readonly [string, PriceQuote | null][];
}

const MEMORY_LIMIT = 12;
const memory = new Map<string, StoredAnalysis>();

function analysesDir(): string {
  return path.join(getRuntimeConfig().stateDir, 'analyses');
}

function filePath(id: string): string {
  // The id is generated by randomUUID, never user input, but validate anyway:
  // this value becomes a filesystem path.
  if (!/^[0-9a-f-]{36}$/i.test(id)) throw new Error('Invalid analysis id');
  return path.join(analysesDir(), `${id}.json`);
}

export function isValidAnalysisId(id: string): boolean {
  return /^[0-9a-f-]{36}$/i.test(id);
}

export function saveAnalysis(record: StoredAnalysis): void {
  memory.set(record.result.id, record);
  while (memory.size > MEMORY_LIMIT) {
    const oldest = memory.keys().next().value;
    if (oldest === undefined) break;
    memory.delete(oldest);
  }
  try {
    mkdirSync(analysesDir(), { recursive: true });
    writeFileSync(filePath(record.result.id), JSON.stringify(record));
    pruneOldAnalyses();
  } catch {
    // Persisting is best-effort. The in-memory copy still serves this session.
  }
}

export function loadAnalysis(id: string): StoredAnalysis | null {
  if (!isValidAnalysisId(id)) return null;
  const cached = memory.get(id);
  if (cached) return cached;
  try {
    const raw = readFileSync(filePath(id), 'utf8');
    const record = JSON.parse(raw) as StoredAnalysis;
    memory.set(id, record);
    return record;
  } catch {
    return null;
  }
}

export function analysisExists(id: string): boolean {
  if (!isValidAnalysisId(id)) return false;
  if (memory.has(id)) return true;
  try {
    return existsSync(filePath(id));
  } catch {
    return false;
  }
}

/** Keep the state directory from growing without bound during development. */
function pruneOldAnalyses(keep = 60): void {
  try {
    const dir = analysesDir();
    const files = readdirSync(dir)
      .filter((f) => f.endsWith('.json'))
      .map((f) => ({ file: f, mtime: statSync(path.join(dir, f)).mtimeMs }))
      .sort((a, b) => b.mtime - a.mtime);
    for (const entry of files.slice(keep)) {
      unlinkSync(path.join(dir, entry.file));
    }
  } catch {
    // Ignore: pruning is housekeeping, not correctness.
  }
}

/** Test hook. */
export function clearAnalysisMemory(): void {
  memory.clear();
}
