/**
 * Internal representation of an LDraw document.
 *
 * Design goals, in priority order:
 *  1. Byte-exact round-trip of anything we did not deliberately change.
 *  2. Never lose an unrecognised line. Unknown metadata and malformed lines are
 *     preserved verbatim as `raw` and re-emitted untouched.
 *  3. Enough structure to address a single physical part instance and mutate
 *     exactly the line that produced it.
 */

import type { Mat3, Vec3 } from './math';

export type LDrawCommandType =
  | 'blank'
  | 'meta'
  | 'part'
  | 'line'
  | 'triangle'
  | 'quad'
  | 'optionalLine'
  | 'malformed';

interface LDrawCommandBase {
  readonly type: LDrawCommandType;
  /**
   * The original source line, without its line terminator.
   * `null` means "this command was created or modified programmatically and must
   * be regenerated by the serializer".
   */
  readonly raw: string | null;
  /** 1-based line number in the source document. -1 for synthesised commands. */
  readonly sourceLine: number;
}

/** A blank (whitespace-only) line. Legal LDraw, carries no meaning. */
export interface BlankCommand extends LDrawCommandBase {
  readonly type: 'blank';
}

/**
 * Any line type 0. This covers plain comments, `0 // ...`, `0 STEP`,
 * `0 FILE <name>`, `0 !LICENSE ...` and every other META command, official or
 * not. `keyword` is the first token after the `0` uppercased, which is enough to
 * recognise the handful of commands we care about while treating the rest as
 * opaque.
 */
export interface MetaCommand extends LDrawCommandBase {
  readonly type: 'meta';
  /** Uppercased first token after `0`, e.g. `STEP`, `FILE`, `!LICENSE`. `''` for a bare `0`. */
  readonly keyword: string;
  /** Everything after the keyword, trimmed. */
  readonly args: string;
  /** Full text after the leading `0`, trimmed. Useful for plain comments. */
  readonly text: string;
}

/** Line type 1: a reference to a part or submodel. */
export interface PartCommand extends LDrawCommandBase {
  readonly type: 'part';
  readonly colorId: number;
  readonly position: Vec3;
  readonly matrix: Mat3;
  /** The filename exactly as written, e.g. `s\3001s01.dat` or `Main Model.ldr`. */
  readonly file: string;
}

/** Line types 2-5: raw geometry inside a part file. */
export interface GeometryCommand extends LDrawCommandBase {
  readonly type: 'line' | 'triangle' | 'quad' | 'optionalLine';
  readonly colorId: number;
  /** Flat list of coordinates: 6 for line, 9 for triangle, 12 for quad/optional line. */
  readonly coords: readonly number[];
}

/** A line we could not parse. Preserved verbatim, reported as a warning. */
export interface MalformedCommand extends LDrawCommandBase {
  readonly type: 'malformed';
  readonly reason: string;
}

export type LDrawCommand =
  | BlankCommand
  | MetaCommand
  | PartCommand
  | GeometryCommand
  | MalformedCommand;

export interface ModelFile {
  /**
   * Sub-file name. For a named MPD block this is the argument of `0 FILE`,
   * preserved with original case. For the implicit block of a plain `.ldr` it is
   * the document's own filename.
   */
  readonly name: string;
  /**
   * True when this block was not introduced by a `0 FILE` line - i.e. the
   * leading block of a plain `.ldr`, or content following `0 NOFILE`.
   * Anonymous blocks other than the first are not addressable as submodels.
   */
  readonly isAnonymous: boolean;
  /**
   * All commands in document order. For a named block this INCLUDES its own
   * `0 FILE` line as commands[0], and a terminating `0 NOFILE` if present, so
   * that concatenating every file's commands reproduces the source exactly.
   */
  commands: LDrawCommand[];
  /** Value of a `0 Name:` header line, if present. */
  readonly headerName: string | null;
  /** Value of a `0 Author:` header line, if present. */
  readonly author: string | null;
  /** First non-empty `0` line that is not a recognised meta command - the model title. */
  readonly description: string | null;
}

export type ParseWarningCode =
  | 'malformed_line'
  | 'duplicate_file_name'
  | 'empty_document'
  | 'truncated'
  | 'unsupported_line_type'
  | 'nofile_without_file';

export interface ParseWarning {
  readonly code: ParseWarningCode;
  readonly message: string;
  readonly line: number;
  readonly file: string | null;
}

export interface LDrawDocument {
  /** All blocks in document order. */
  readonly files: ModelFile[];
  /** Name of the main model: the first named block, else the first block. */
  readonly rootFile: string;
  /** True if the document contained at least one `0 FILE`. */
  readonly isMpd: boolean;
  /** Line ending detected in the source, reused on serialization. */
  readonly lineEnding: '\n' | '\r\n';
  /** Whether the source ended with a line terminator. */
  readonly trailingNewline: boolean;
  /** Bounded: see MAX_WARNINGS in parser.ts. */
  readonly warnings: ParseWarning[];
  /** Total malformed lines, counted rather than derived from `warnings`. */
  readonly malformedLineCount: number;
  /** Warnings beyond the cap, which are counted but not kept. */
  readonly suppressedWarningCount: number;
  /** Name the document was loaded under (upload filename or fixture name). */
  readonly sourceName: string;
}

// ---------------------------------------------------------------------------
// Flattened representation
// ---------------------------------------------------------------------------

/**
 * One physical part in the completed model.
 *
 * `commandRef` is the single most important field: it identifies the exact
 * line type 1 that produced this instance. Because a submodel may be referenced
 * more than once, several PartInstances can share one commandRef - editing that
 * line changes all of them. The optimizer groups candidates by commandRef for
 * exactly this reason (see src/lib/optimizer/candidates.ts).
 */
export interface PartInstance {
  /** Unique within a model. Encodes the full reference path, so it is stable across re-parses. */
  readonly instanceId: string;
  /** Normalized part id: lowercase, `.dat` stripped, `\` -> `/`. e.g. `3001`. */
  readonly partId: string;
  /** The reference exactly as written on the line. */
  readonly partFile: string;
  /** Effective color after resolving color 16 (inherit) up the reference chain. */
  readonly colorId: number;
  /** Color as written on this line, before inheritance resolution. */
  readonly declaredColorId: number;
  readonly position: Vec3;
  readonly transformation: Mat3;
  /** 0-based build step within `parentModel`. */
  readonly stepIndex: number;
  /** Name of the sub-file that contains the line. */
  readonly parentModel: string;
  /** Path of sub-file names from the root down to `parentModel`. */
  readonly modelPath: readonly string[];
  /** Nesting depth: 0 for a part referenced directly by the root model. */
  readonly depth: number;
  readonly commandRef: CommandRef;
}

/** Addresses one command inside one sub-file of a document. */
export interface CommandRef {
  /** Index into LDrawDocument.files. */
  readonly fileIndex: number;
  /** Index into ModelFile.commands. */
  readonly commandIndex: number;
}

export function commandRefKey(ref: CommandRef): string {
  return `${ref.fileIndex}:${ref.commandIndex}`;
}

export interface UnresolvedReference {
  /** Reference as written. */
  readonly file: string;
  /** Normalized id used for lookup. */
  readonly partId: string;
  /** Number of times it appears. */
  readonly count: number;
  readonly reason: 'not_in_document' | 'not_in_library';
}

export interface ResolvedModel {
  readonly document: LDrawDocument;
  readonly instances: PartInstance[];
  /** Submodel references that could not be resolved inside the document. */
  readonly unresolvedSubmodels: string[];
  /** Total number of build steps in the root model. */
  readonly rootStepCount: number;
  /** Number of distinct sub-files actually reachable from the root. */
  readonly submodelCount: number;
  readonly warnings: ParseWarning[];
  /** True when expansion hit a configured limit and the result is partial. */
  readonly truncated: boolean;
  readonly truncationReason: string | null;
}
